language: go

matrix:
  include:
    - go: "1.10.x"
    - go: "1.11.x"
      env:
        - GO111MODULE=on
      install: true
    - go: "1.12.x"
      env:
        - GO111MODULE=on
      install: true
script:
  - npm install -g serverless
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic -tags=remote

after_success:
  - bash <(curl -s https://codecov.io/bash)